name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  ci_main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Aptitude Dependencies
        run: |
          sudo apt install -y tar wget make gcc clang python3 openmpi-* python-dev

      - name: Fetch & Install Dependencies (/installers)
        run: |
          cd installers
          sh ./install_fftw.sh   -j 4
          sh ./install_lapack.sh -j 4
          sh ./install_hdf5.sh   -j 4
          sh ./install_silo.sh   -j 4
          cd ..
      
      - name: Build MFC
        run: make -j 4
      
      - name: Run MFC Tests
        run: make test