name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Clone MFC
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: Fetch Aptitude Dependencies
        run: |
          sudo apt install -y tar wget make cmake gcc g++ python3 openmpi-* python python-dev python3-dev libopenmpi-dev
          pip3 install pyyaml colorama

      - name: Build MFC and its dependencies (mfc.py)
        run: |
          chmod +x ./mfc.py
          ./mfc.py -t MFC -cc ci -j $(nproc)
      
      - name: Run MFC Tests
        run: ./tests/checks.sh

      - name: Upload logs
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: mfc-py-logs
          path: .mfc/**/log/
