name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch Aptitude Dependencies
        run: |
          sudo apt install -y tar wget make gcc clang python3 openmpi-* python python-dev python3-dev

      - name: Fetch & Install Dependencies (/dependencies)
        run: |
          cd dependencies
          ./install.sh -j $(nproc)
          cd ..
      
      - name: Build MFC
        run: make -j $(nproc)
      
      - name: Run MFC Tests
        run: make test
